### ISSUE TITLE
Any critical issues with the previous V3 Sweep?

### ISSUE THREAD

**Issue by matru** [climent/SouffleKeyboard#2]
Hey, thanks for your work on the board. I have one laying around since last year, I believe it's the V3 of the MX version and I am wondering if it's safe (of issues) to build. 

I see now there are some fixes "[Updated and fixed v3.2 as the order of the pads was incorrect.](https://github.com/climent/SouffleKeyboard/commit/4ca09d7c8aaca1b14398b6fbeec5d10cdc3c8563)". What pads are affected here, since previously to that a NiceView option was added?

**Comment by climent** [comment]
What version of the keyboard you have? It should be in the corner of the board. If it either says "v3-sweep" or "v3.2.1-sweep" you should be fine. The problem with the v3.2 was specific to the OLED screen, where the pads were created in the wrong order, but everything should work fine.

**Comment by matru** [comment]
On the pcbs it says v3-sweep indeed. But from what I can see, I have a version before the commit "Update tracks and moved boards to KiCad 7.x". 

I already had it August/Sept 2023.

**Comment by climent** [comment]
It should be fine. The update was mostly aesthetic, and should not affect functionality. I currently (typing this text) using a board that is similar to yours without any problem.

**Comment by matru** [comment]
@climent thanks a lot, I really needed to make sure if everything would be fine, since I will also be selling the rest of my pcbs and saving one for me and a friend.

**Comment by climent** [comment]
You can confirm it by checking how many holes you have for the OLED pins. if it is 4, you are 100% good.

![image](https://github.com/user-attachments/assets/f5c9f1ea-88c5-4407-9df4-4e5ec11b97c9)

**Comment by matru** [comment]
Nice, I got them. Btw any issues not soldering the jumper pads for them if I don't use any OLED screens?

**Comment by climent** [comment]
No issues at all. The pads are to connect either side of the OLED screens, so not soldering is not a dealbreaker if you are not using them.
